### ISSUE TITLE
Luxmark 2.0 how to download / compile

### ISSUE THREAD

**Issue by mrkapqa** [LuxCoreRender/LuxMark#2]
Hello ,

ia am looking for this program with "sala" scene to download / compile for MacOSX.

Thank you

**Comment by Dade916** [comment]
LuxMark v2.0 was still included in LuxCore sources repository at the time. It is available inside https://github.com/LuxCoreRender/LuxCore repository at the tag "luxmark_v2.0": https://github.com/LuxCoreRender/LuxCore/tree/luxmark_v2.0/samples/luxmark

The "Sala" scene is available here: https://github.com/LuxCoreRender/LuxCore/tree/luxmark_v2.0/samples/luxmark/scenes/sala

But it is quite old stuff, written more than 6 years ago, it may be hard to compile nowadays.

Any particular reason to use v2.0 instead of latest v3.1 ?

**Comment by mrkapqa** [comment]
thank you ,

nothing particular, i use older hardware , so i wanted to test against some benchmarks that were posted online using the "sala" scene,
and i like when older software remains still accessible, especially when newer software has removed some features that were previously included.

Grazie!

**Comment by mrkapqa** [comment]
can i just download the "sala" scene and include it in the directory of the Luxmark Program on Osx?

**Comment by Dade916** [comment]
I'm afraid the v2.0 binaries has been lost when the old luxrender.net site was hacked. So the only way to run the old benchmark is to re-compile the sources (a quite complex task).

You can not just use the scene with the new software because the results would be not comparable with the old version (due to different optimizations, features, etc.).

**Comment by mrkapqa** [comment]
thanks, i am also learning to make backups !

all the best.

**Comment by Randrianasulu** [comment]
Some old binaries live in Wayback Machine on Internet Archive, tested win32 Luxmark 2.0 on rusticl/Linux in wine ;)

https://web.archive.org/web/*/http://www.luxrender.net/release/luxmark/*
