### ISSUE TITLE
division by zero with default compilation options produced artefacts

### ISSUE THREAD

**Issue by BenjaminCoquelle** [LuxCoreRender/LuxMark#9]
We recently found a bug in Luxmark3.1

The kernel code has the following
min(1.f, lastPdfW / PARAM_PDF_CLAMP_VALUE);

While by default the variable PARAM_PDF_CLAMP_VALUE is set to 0 during OpenCL kernel compilation time, see below the constants passed
....-D PARAM_RADIANCE_CLAMP_MAXVALUE=0.000000e+000f **-D PARAM_PDF_CLAMP_VALUE=0.000000e+000f** -D PARAM_IMAGE_FILTER_TYPE=2...

When -cl-fast-relaxed-math is enabled it can produce undefined behaviour as this compiler option triggers the -finite-math-only and the compiler is not supposed to handle division by zero (inf cases) properly

https://www.khronos.org/registry/OpenCL/specs/2.2/html/OpenCL_API.html#compiler-options
-cl-finite-math-only
Allow optimizations for floating-point arithmetic that assume that arguments and results are not NaNs, +Inf, -Inf. This option may violate the OpenCL numerical compliance requirements for single precision and double precision floating-point, as well as edge case behavior. The original and modified values are defined in the SPIR-V OpenCL environment specification

-cl-fast-relaxed-math
Sets the optimization options -cl-finite-math-only and -cl-unsafe-math-optimizations. This option causes the preprocessor macro __FAST_RELAXED_MATH__ to be defined in the OpenCL program.

These options are actually the default for luxmark3.1

**Comment by Dade916** [comment]
I'm working on a new version of LuxMark (v4.0 => https://github.com/LuxCoreRender/LuxMark/commits/master). It is based on LuxCoreRender v2.5. The (OpenCL/CUDA) kernel code is far more recent (in the order of many years newer) and it doesn't include PDF clamping anymore (it has been replaced by variance clamping).

So I'm going to mark this as a "bug" (for future references) but also as "wontfix" because there is not going to be a maintenance release of very old v3.1.
